import { LessonTopic } from '../types';

export const LESSON_TOPICS: LessonTopic[] = [
  {
    id: 'alephbet',
    emoji: '🔤',
    hebrewTitle: 'אָלֶף-בֵּית',
    transliteration: 'Aleph-Bet',
    englishTitle: 'Hebrew Alphabet',
    description: 'Learn the 22 letters',
    promptHint: "I want to learn the Hebrew alphabet (אָלֶף-בֵּית)! Let's start from the beginning!",
  },
  {
    id: 'numbers',
    emoji: '🔢',
    hebrewTitle: 'מִסְפָּרִים',
    transliteration: 'Misparim',
    englishTitle: 'Numbers',
    description: 'Count 1 to 20',
    promptHint: "I want to learn numbers in Hebrew (מִסְפָּרִים)! Let's count together!",
  },
  {
    id: 'colors',
    emoji: '🎨',
    hebrewTitle: 'צְבָעִים',
    transliteration: 'Tzvaim',
    englishTitle: 'Colors',
    description: 'Colors of the rainbow',
    promptHint: "I want to learn colors in Hebrew (צְבָעִים)! 🌈",
  },
  {
    id: 'greetings',
    emoji: '👋',
    hebrewTitle: 'בְּרָכוֹת',
    transliteration: 'Brachot',
    englishTitle: 'Greetings',
    description: 'Say hello & goodbye',
    promptHint: "I want to learn Hebrew greetings (בְּרָכוֹת)! How do I say hello?",
  },
  {
    id: 'family',
    emoji: '👨‍👩‍👧',
    hebrewTitle: 'מִשְׁפָּחָה',
    transliteration: 'Mishpacha',
    englishTitle: 'Family',
    description: 'Mom, dad, siblings...',
    promptHint: "I want to learn family words in Hebrew (מִשְׁפָּחָה)!",
  },
  {
    id: 'animals',
    emoji: '🐘',
    hebrewTitle: 'חַיּוֹת',
    transliteration: 'Chayyot',
    englishTitle: 'Animals',
    description: 'Zoo animals & pets',
    promptHint: "I want to learn animal names in Hebrew (חַיּוֹת)! 🦁",
  },
  {
    id: 'food',
    emoji: '🍎',
    hebrewTitle: 'אֹכֶל',
    transliteration: 'Ochel',
    englishTitle: 'Food',
    description: 'Yummy Hebrew words',
    promptHint: "I want to learn food words in Hebrew (אֹכֶל)! I'm hungry to learn! 🍕",
  },
  {
    id: 'days',
    emoji: '📅',
    hebrewTitle: 'יְמֵי הַשָּׁבוּעַ',
    transliteration: 'Yemei HaShavua',
    englishTitle: 'Days of the Week',
    description: 'Every day of the week',
    promptHint: "I want to learn the days of the week in Hebrew (יְמֵי הַשָּׁבוּעַ)!",
  },
];
